### ISSUE TITLE
Aliases for common non-ASCII characters

### ISSUE THREAD

**Issue by apblack** [gracelang/language#18]
It's nice to use non-ASCII characters like `≠`, `≤` and so on, for operators.  Currently, this can be supported by a library if the library-writer wants to, but such support is inevitably non-uniform, since it depends on the library writer.  Do strings support `≤` as well as `<`?  Do they do the same thing?  Do I need to override one or both in sub-objects?  If one, which one?

An alternative would be for the _language_ to define equivalencies, so that the ≠ operator symbol and the != operator symbol are always treated as equivalent, and the client can write one while the library implementor writes the other.  Essentially, the parser would exchange one symbol for the other.

This would result in more uniformity than the current situation, and less code.  If we defined [[ and ]] as equivalent to ⟦ and ⟧, that would open the way to stopping using < and > as brackets, which is pretty horrible.

**Comment by KimBruce** [comment]
This seems like a good idea to me.  It allows code to be more readable,
while also continuing to make it more easily typable.

**Comment by kjx** [comment]
I’ve always though C++ trigraphs were a very bad idea.

When I first read this email (on my phone) the post-ASCII characters only appeared as boxes :-)

I think we have three choices here:

 - reiterate the choice to remain within ASCII - so *novices* can at least work out what to type
   - move any existing post-ascii characters (except for special cases) back to Ascii
 
 - adopt full post-ascii.   ideally have a set of standardisze *input* conventions that alway render as unicode
     (so people type == and get whavever unicode “=“ we want)
     presentation typesetting is fine, so long as it’s clearly closly related to the ascii version

   - the first thing we have to teach people - and the inside cover of every textbook - must be a list of input character combinations
      (kind of like the LaTex) operator list…

 - keep both. seems like the worst of both worlds, PLUS we’d need a style guide telling people which one to use

I still vote strongly for ASCII subset of unicode for core language and libraries.

J

**Comment by apblack** [comment]
Since this discussion petered out, we have found at least two situations where kjx's determination to remain within ASCII has introduced space-sensitivity as a way of resolving ambiguities. (The situations [ and ] as both an operator and Iterator syntax, and < and > as both operator and type brackets).  I think that space-sensitivity is far worse than either non-ASCII symbols or multi-character symbols.

Personally, I don't see why allowing both ASCII mutli-character symbols (like >=) to be aliases for non-ASCII symbols (like ≥) is the "worst of both worlds".  If we had made more progress with an IDE that provided buttons for entering non-ASCII characters, it wouldn't even be necessary.    It seems like a compromise designed to alienate the fewest number of instructors.

**Comment by KimBruce** [comment]
Two different responses to this:
1.  I like the idea of having some aliases of non-ascii characters to combinations of ascii, e.g. <= and ≤ (though I see that the non-ascii characters do not show up on my phone, alas).

2.  I'm also not a big fan of the space rules for <, >.  I'd personally stop using [ and ] for subscripts and just as "at()" and "at()put()".  Then we could reserve [, ] for type parameters.

Kim

**Comment by kjx** [comment]
> On 12/01/2016, at 13:31pm, Kim Bruce <notifications@github.com> wrote:
> 
>  �����≤ (though I see that the non-ascii characters do not show up on my phone, alas).

and there’s one big reason, again, to stay within ASCII

> If we had made more progress with an IDE that provided buttons for entering non-ASCII characters, it wouldn't even be necessary

and here’s the other one. 


is there a compelling reason to reconsider this?

James,

**Comment by kjx** [comment]
> On 12/01/2016, at 11:28am, Andrew Black <notifications@github.com> wrote:
> 
> space-sensitivity as a way of resolving ambiguities. (The situations [ and ] as both an operator and Iterator syntax, and < and > as both operator and type brackets). I think that space-sensitivity is far worse than either non-ASCII symbols or multi-character symbols.

I’m happy with multi-character symbols / operators, but see that as mostly orthogonal to space sensitivity.

After getting used to it, I quite like the “space around every (infix) operator” rule that Kernan enforces.
I found only a couple of places where it made things obiouisly worse (in my incomplete hack on collections).
although there are some other issues with Kernan line-breaking that did cause problems.

I’d probably go further and say that allowing  set   < Number  >       as an alternative to   set< Number >   is also misleading.
I guess the big inconsistency here is whether we permit foo  ( e  ) as an alternative to foo( e )   
(unfortunately the compelling case is foo { f } which we do want to support! 


Kim:
>   I'd personally stop using [ and ] for subscripts and just as "at()" and "at()put()". Then we could reserve [, ] for type parameters.


- but we just took [ ] for literal primitive sequenes to replace varargs.
- what is more crucial: indexing or optional type parameterisation?
- what occours more often in programs?

We could support [[ ]] as double brackets for either type args or literals, but [[ would be a different literal bracket to [ 

J

**Comment by KimBruce** [comment]
[[T]] would be fine by me for type parameters.

**Comment by kjx** [comment]
Kim - you seem to be happy with space sensitivity so that **"[["** is not the same as **"[ ["** or so that **"aa"** is not the same as **"a a"**

but are not happy with space sensitivity so that **a[** is not the same as **"a ["**

**Comment by apblack** [comment]
kjx, are you seriously arguing that because `aa` isn't the same as `a a` (in any language that I've ever met), we should say that `a+1` isn't the same as `a + 1`?

But I must apologize.  It was me that introduced the red-herring of space sensitivity.  This proposal would not get riff of it, since we would still need space sensitivity to distinguish between `a[[T]]` and — `a`  applied to a type argument — and `a [ [T] ]`— `a` applied to a lineup containing a  lineup containing `T`.

Please go back and read the post that opened this issue.  The issue that we should be discussing here is whether we should define a small set of equivalences between easy to type ASCII sequences and what kjx later calls "presentation typesetting".  Specifically, the equivalences that I propose are

ASCII | Typeset
---------| ----------
>=  |  ≥
<=  |  ≤
!=   |  ≠
[[    |  ⟦
]]    | ⟧
->  | →

At this point, that's all that I propose.  I can imagine that we might eventually introduce one or two more, but I can't think of any reason to do so at this time.  It's important that the list is short enough that a student can remember it, and not hav ego resort to looking at a table — at that point it becomes an impediment rather than a an aid. 

Notice space sensitivity is still with us, both because of the bracket example that I just mentioned, and because `>>=` as an operator is not the same as `>≥`.  In other words, for the above mapping to apply, the surrounding characters would have to be from a different character class.

**Comment by kjx** [comment]
Answering just the question for now: I'm completely against. I'm sorry I didn't word [my comment above](https://github.com/gracelang/language/issues/18#issuecomment-128681659) to make that much clearer.

Pragmatically - if you want to put this in, well fine, but surely there are higher priorities. 

I may get back to the discussion later, in a comment below if Andrew doesn't mind.

**Comment by kjx** [comment]
here's my rationale, such as it is. I haven't the patience to "thread mode" this explicitly.

### presentation syntax
presentation syntax (as I understand it, I'm thinking Lisp M-epressions or what listings,sty does) is a different thing from this proposal: changing the core "input" syntax as well as output syntax.  I Don't mind how your IDE or book shows grace code, but I want it to be clear what the canonical version is. 

### input syntax
I think every symbol that is required should be easily visible on at keyboard.

### don't contort the language because we don't have a good IDE
Your IDE can (and probably should) accept >= and typeset it as ≥ 
or do we mean ≧ I just the same way everything accepts :-) and 
typsets it as 😀.  But that's not a good reason for replacing 
:-) with 😀, or keeping both in the ore syntax of a programming language. 


### spacing
`a+1` is a varia≧le in Lisp derived languages, inclding Pyret.  My point is that we can decide where and when we want to be space sensitive, and where not. 

### slippery slope
I think there are lots more we will want. Basically this is setting up a set of equivalence classes between sequences of unicode operator characters. It will infect most/all of the language. E.g. I noticed some mac app making unicode smart “double quotes”  — OK that is Mac Mail 8.2 that I’m using now, look at the two quotes in this line!   It’s getting harder to type just ascii quotes, so clearly the Right Thing to do is to accept any unicode quote-ish symbol as a synonym to the standard double-quote...   Again, I think Algol-68's short and long forms, and C++ trigraphs are clearly bad ideas

### traits can almost do it.
Using traits, I think you can get almost what you want **in libraries**  Just define a “operators-aliases” trait or two, that defines the unicode operators in terms of the ascii operators, and mix that trait in to everything. (Note that this is trait where traits silently overriding classes is probably the wrong thing #38).
If we can do (most of) it in libraries, why put it in the language now?

**Comment by apblack** [comment]
I was tempted to say that I'm giving up on this, because kjx is evidently opposed, and that will kill the proposal.  But I'm not going to, because kjx has taken over this issue to advocate something that is, in my view, _far more dangerous_: that in IDEs, books and other "presentation" modes, we should distort programs by, for example, typesetting a program continuing >= as if it contained ≥.

 * This is dangerous because a student copying a program out of the book, or cutting and pasting it, will find that the program doesn't work.

 * This is dangerous because if I actually do as kjx suggests, and write a trait that, for example, defines method ≥ to forward to method >=, then that trait will be a syntax error after being "presented".  This trait will also appear to define something in terms of itself, and it will be impossible to see if it's defining >= in terms of ≥, or ≥ in terms of >= .  And this is something that its user _must know_ if the trait is to be used correctly.

 * This is dangerous because it makes it unclear how to type the canonical version (exactly kjx's first point above).

 * This is dangerous because the set of equivalences implemented by the IDE, or the typesetter, or the book editor, is _not_ part of the language definition, but will vary from one medium to another.

For these reasons, I think that this is a Bad Idea. I have carefully avoided setting up my slides and papers to do anything more severe than adjusting the kerning in >>=.

A small set of equivalences defined as part of the language will avoid all of these problems.

By the slippery slope argument, I'm not sure if kjx means the wedge, or the dangerous precedent.  Cornford writesª as follows:

> Two other arguments of universal application have been added to the rhetorical armoury ... . They are called the _Wedge_ and the _Dangerous Precedent_. Though they are very familiar, the principles, or rules of inaction, involved in them are seldom stated in full. They are as follows.

> The _Principle of the Wedge_ is that you should not act justly now for fear of raising expectations that you may act still more justly in the future — expectations which you are afraid you will not have the courage to satisfy. A little reflection will make it evident that the Wedge argument implies the admission that the persons who use it cannot prove that the action is not just. If they could, that would be the sole and sufficient reason for not doing it, and this argument would be superfluous.

> The _Principle of the Dangerous Precedent_ is that you should not now do an admittedly right action for fear you, or your equally timid successors, should not have the courage to do right in some future case, which, ex hypothesi, is essentially different, but superficially resembles the present one. Every public action which is not customary, either is wrong, or, if it is right, is a dangerous precedent. It follows that nothing should ever be done for the first time.

ª F. M. Cornford. _Microcosmographia Academica, Being A Guide For The Young Academic Politician_. Bowes & Bowes, Cambridge, 1908.

**Comment by kjx** [comment]
> kjx is evidently opposed, and that will kill the proposal

I am 'opposed in principle', but I will not kill this proposal or any other.  If you want it, go for it. Put it in the markdown spec and in AMG. 


>This is dangerous because a student copying a program out of the book, or cutting and pasting it, will find that the program doesn't work.

Yes, this is really critical - certainly contorting in an IDE or on paper _and simultaneously_ defining in them traits won't work.  But that is a problem with any non-basic-ascill "presentation". Contorting IDEs would presumably cut-and-paste the raw-ascii version.

> the set of equivalences implemented by the IDE, or the typesetter, or the book editor, is not part of the language definition,

We put such a table into the spec (ala M-expressions again)  without committing us to any implementation effort.  

------
### Unhelpful ranting: 

> because kjx has taken over this issue

I'm sorry if you think I've "taken over the issue" or am "advocating" or "unhelpfully ranting".  If anything, I'm advocating (first preference) doing nothing at all, with (second preference) an option of IDE support in some indefinite future --- both of which seem (to me at least) to be relevant to the question of whether Grace should do this or not.     

I **do not want to kill anything** you and Kim feel strongly about any more. I want to make progress rather than embarrass myself publicly in front of anyone who are now waiting for the spec. 

> By the slippery slope argument, I'm not sure if kjx means the wedge, or the dangerous precedent. Cornford writesª as follows:

I meant the Slippery Slope: https://en.wikipedia.org/wiki/Slippery_slope: 

> asserts that a particular result will probably (or even must inevitably) follow from a given decision  ...
> without necessarily providing any rational argument or demonstrable mechanism for the likelihood of the assumed consequence ...
> This type of argument is sometimes used as a form of fear mongering, 

and meant to indicate this was not a strong argument.
