### ISSUE TITLE
Extending an existing class

### ISSUE THREAD

**Issue by apblack** [gracelang/language#25]
Suppose I wish to extend an existing class.  For example, I want to extend list by adding a binary search method.

I can write a new _list_ module that contains a new factory method _withAll(elements)_, which inherits from the prelude's _list.withAll(elements)_.  I can add some methods.  All seems fine.

The problem comes on inherited methods that return new lists.  The receiver that these methods use to create a new list (for example, list in list.empty, or lazyEnumeration.trait, or whatever ...) is _statically bound_.  So, although client code seems to get a working list extended with binary search, every time it gets a new list by requesting extendedList ++ otherList, or .asList, or ... it will get an old, non-extended list.

In Smalltalk, the solution is to write the original list code so that it generates new lists using the factory object species.  This seems to require a more complete type system than we have previously envisaged.

**Comment by kjx** [comment]
> I can write a new lits module that contains a new factory method withAll(elements), which inherits from the prelude's list.withAll(elements). I can add some methods. All seems fine.
> 
> The problem comes on inherited methods that return new lists. The receiver that these methods use to create a new list (for example, list in list.empty, or lazyEnumeration.trait, or whatever ...) is statically bound. 

sure. the question is *when* is it statically bound, and how many definitions of “list” exist in the "final system."

> So, although client code seems to get a working list extended with binary search, every time it gets a new list by requesting extendedList ++ otherList, or .asList, or ... it will get an old, non-extended list.

If there are two (or more) versions of “list” in the system this problem seems unavoidable. 
I asked Gilad if Newspeak had an analogous problem (dinner in Athens after the meeting I think) and he said it did.

on the other hand, in Kernan, or NewSpeak, most of the time you shouldn’t have this problem. 
You should be able to supply an updated collection module (or list module) when the system is composed
and everything should bind (albeit “statically”) to the updated module. 

The really interesting question is how do you write - or bind - the import statement in the extending module.

this is why we should talk about importing at some point.

James

**Comment by KimBruce** [comment]
This is an interesting and challenging question.  The issue is really inheritable constructors.  Nate Foster and I addressed the question on our language LOOJ, and ended up deciding that it wasn't that much harder to program around the issue.  Others have given a variety of ways of getting inheritable constructors.  (I've put in the svn repository backgroundPapers a paper by Ryu on ThisType which includes inheritable constructors.)  

The bottom line is that you can do it, but it requires careful planning in advance (or rewriting of code once you decided to do this).  The good part is that with some work, it is possible because it involves a covariant change in return types.  It's just not as easy on the programmer as you would like.

There are also other proposals (by me among others) that involve mutual specialization of a group of classes.  The idea is to put them all in an object and then extend them all simultaneously.  I'm not sure any of these are necessary for a language for novices (at least not the core version), but we can discuss them.

**Comment by apblack** [comment]
I don't understand a lot of what you wrote above.   Does NewSpeak have this problem or not?  I would have thought that NewSpeak, like Smalltalk, would make it easy to program in a style that avoids it.

It seems clear that there must be at least 2 `list` factory objects in the final system, since one inherits from the other.   I don't see why this makes it inevitable that internal uses of `list` in the original one can't be parameterized so as to use the other.   If noting else, the "self factory" object could be made an explicit parameter.

**Comment by kjx** [comment]
> On 1/09/2015, at 16:17pm, Andrew Black <notifications@github.com> wrote:
> 
> I don't understand a lot of what you wrote above. Does NewSpeak have this problem or not?

As I understand it, it is possible to set up a Newspeak system so that there are two versions of classes and sometimes the ‘wrong’ one gets used - particularly where system primitives (that communicate with the underlying Smalltalk platform) are used

> I would have thought that NewSpeak, like Smalltalk, would make it easy to program in a style that avoids it.

Old Smalltalk avoids it by letting people directly modify the classes in the IDE
Newer Smalltalk avoids it via the module system (or so I understand)
Ruby avoids it with officially open classes where you have syntax to load in class extensions

> It seems clear that there must be at least 2 list factory objects in the final system, since one inherits from the other.

yep. the question is what are they called or how are they bound.

> I don't see why this makes it inevitable that internal uses of list in the original one can't be parameterized so as to use the other. If noting else, the "self factory" object could be made an explicit parameter.

right - which is what Newspeak does, and Newspeak can apparently be configured that the right “list class” object ends up in the right place.

we should be able to do the same - modulo the invariant in the module system that the same name always resolves to the same instance

J
