### ISSUE TITLE
Allow testing for `undefined` ?

### ISSUE THREAD

**Issue by apblack** [gracelang/language#28]
Most modern languages allow the programmer to test if a variable is undefined.  Should Grace do the same?

I think that this does not affect the type system.  It would remain an error to attempt to read the value of an undefined variable.  The only change would be making it possible to test the precondition of that error. This would enable a programming style in which one could write

```grace
if (isUndefined(myVar)) then { myVar := defaultValue }
```

At present, Grace implicitly encourages the awful (and hard to type-check)

``` grace
var myVar := false
...
if (false == myVar) then { myVar := defaultValue }
```
or the use of an auxiliary variable

``` grace
var myVar 
var myVarIsDefined := false
...
if (myVarIsDefined.not) then { myVar := defaultValue }
```
neither of which is Graceful.

**Comment by KimBruce** [comment]
I used variant types with singletons in order to do this.
type Option<T> = T | nothing
where nothing is defined as a singleton type (with whatever part of T's
behavior desired -- including nothing at all)

The match statement can then easily discriminate between the two kinds of
values, and it forces you to check before trying to use the value with any
operations not supported by both kinds of values.

I greatly prefer this use as it forces you to test before using the value,
whereas the other approach leaves it optional (and easily forgotten).

Of course this is a programming idiom and people can ignore it, but I
personally find it very helpful.

In my opinion touching an undefined variable is a programming error and
should not be treated as something that could be handled like any other
condition.

YMMD

**Comment by apblack** [comment]
I know that you don't use this programming style.  I wan't trying to convince you to do so.  I've never used it either, and was fully on-board with our original decision not to allow checking for undefined.

I'm raising this as an issue now because I've been reading more code online, as a source of inspiration when teaching. Many modern languages do support checking for undefined.  Instructors (other than you) may want to teach it.  Certainly, if students will be programming in JavaScript or Perl or PHP or Ruby they _will_ see this idiom, even if they choose not to follow it.   As with code using `match`, instructors should be able to use Grace to show both coding styles, and compare them, discussing the advantages and disadvantages of each.

**Comment by apblack** [comment]
And if I were to introduce an "isUndefined" method in the prelude?

**Comment by KimBruce** [comment]
I'm not thrilled, but would acquiesce ...

**Comment by kjx** [comment]
Testing for undefined is completely evil. 
Most likely no-one will use Grace anyway, so why contort the design for something we all hate?

If by some chance the language is adopted, this will be a wart.

**Comment by apblack** [comment]
The major use case for testing for undefined is covered by _once methods_.  Since we have agreed to add them, let's close this issue as a _bad idea_.  And move on to choosing a syntax for **once**.
