### ISSUE TITLE
"type" is both declaration and literal

### ISSUE THREAD

**Issue by kjx** [gracelang/language#42]
the **type** keyword is used for two different things: marking out type constructor expressions

```
 type { 
   foo -> Done 
   bar -> Done
 }

```

and declaring types:

```
 type FooBar = { 
   foo -> Done 
   bar -> Done
 }

```

Should we steal Go's design, and change the type constructor keyword to **interface** https://golang.org/ref/spec#Interface_types . This would give us 

```
 interface { 
   foo -> Done 
   bar -> Done
 }

```

and declaring types:

```
 type FooBar = interface { 
   foo -> Done 
   bar -> Done
 }

```

**Comment by kjx** [comment]
If **interface** is to long, we could use **struct** or **functor** :-)

**Comment by apblack** [comment]
I don't see any problem with using the same keyword to mean multiple things in different contexts.  In general, the fewer keywords the better, since a word reserved to be a keyword can't be used for any other purpose.

`interface` _is_ too long.  We also want to get students to understand that in OO languages, types **_are_** interfaces, not structures.   Right now I can stand in front of a class and say "types are interfaces".  If we use the word interface to mean something else, then I can't say that any more without being guilty of moral turpitude. (See Reynolds' ["Types, Abstraction and Parametric Polymorphism"](http://www.cse.chalmers.se/edu/year/2010/course/DAT140_Types/Reynolds_typesabpara.pdf))

**Comment by KimBruce** [comment]
I was sad when we were forced to introduce type on the right side of type declarations, e.g.,

type A = B & type {
    …
}

because of parsing issues (ambiguity) and wish we could go back to leaving it off.  I agree with Andrew that it’s OK in this situation to use the same keyword twice.  Let’s leave it as it is.

**Comment by kjx** [comment]
> `interface` is too long. 

It's longer than I'd like, but Go has picked it. 

> Right now I can stand in front of a class and say "types are interfaces"

```
type T = interface { 
   blah 
}
```

reads to me like _type T is the following interface!_

> We also want to get students to understand that in OO languages, types are interfaces, not structures. 

But in Grace, unless we change something, **type are not just interfaces**.   In one of the last remaining algebraic features, our retained union `type T = A | B` retains memory that T is either an A and B, in a way that `type T = A + B` does not.   You can't explain `A | B` as just an interface.

**Comment by apblack** [comment]
> But in Grace, unless we change something, type are not just interfaces. In one of the last remaining algebraic features, our retained union type T = A | B retains memory that T is either an A and B, in a way that type T = A + B does not. You can't explain A | B as just an interface.

You are right.  I hate that too.  Do you want to open another issue to get rid of it?



.

**Comment by kjx** [comment]
Andrew - not when Kim has just commented on #14 that here prefers using | to any kind of Maybe.

**Comment by kjx** [comment]
Kim - I recall it's not just a `parsing` issue, it's also about language design.

{ } brackets without a directly preceding keyword mean blocks inside methods.
Outside methods, they're also used to group method bodies etc technically after the method keyword.

**Comment by apblack** [comment]
Ok, I guess that I'll have to learn to say that a _type literal_ describes an interfere, whereas a _type_ is, technically, a disjunction of interfaces.

But I still think that we can keep the **type** keyword for both.

**Comment by kjx** [comment]
We can keep the **type** keyword for both: the question is whether we should or not?

**Comment by apblack** [comment]
I don't see an overpowering reason to change it.

**Comment by apblack** [comment]
I've changed my mind about this.  Why?  Because I'm thinking about teaching about interfaces and types.

What we have been calling type literals actually describe interfaces, and in Grace, while interfaces are types, types are not interfaces but disjunctions of interfaces.  This would be easier to teach if we used different names for the different concepts.

**Comment by KimBruce** [comment]
Types are essentially disjunctions of interfaces.  That is how we defined them.  90% of the time it is a single interface, but sometimes it is more.  I don't see that as a problem.

**Comment by kjx** [comment]
I wonder if *Interface* seems like a long word, as in: 

```
type Foo = interface { 
    blah
}
```

other options are *signature*, which nicely abbreviates to *sig*. 

```
type Foo = sig {
   d
   c
   b 
}
```

**Comment by apblack** [comment]
I like using "signature" to describe the type of a single method, and interface to describe a set of signatures.  Type would be a disjunction of interface, as [Kim said](https://github.com/gracelang/language/issues/42#issuecomment-206125259), or maybe a disjunction of interfaces or "singles".

I think that it would help to be consistent in our terminology, and for the keywords to match the terminology.

**Comment by kjx** [comment]
> I like using "signature" to describe the type of a single method, and interface to describe a set of signatures.

me too.

**Comment by KimBruce** [comment]
I think we're in violent agreement!  (Though I don't know how to signal it aside from closing this stream.)

**Comment by kjx** [comment]
just to check: violent agreement about changing to "interface" as the keyword for a type literal, and "type" as the keyword for a type declaration

**Comment by KimBruce** [comment]
Yes

**Comment by kjx** [comment]
OK!!  hurrah!
