### ISSUE TITLE
traits 'excludes' and alias clauses syntax

### ISSUE THREAD

**Issue by kjx** [gracelang/language#43]
Similar to #36 do we write
```
uses foo
   exclude m()n(), x()y()
```
or 
```
uses bar
   exclude m()n()
   exclude x()y()
```

Kernan supports only one method per **exclude**

**Comment by kjx** [comment]
This also applies to alias clauses:

we support:
```
   trait foo {
      use trait bar
          alias bar_eq(_) = ==(x) 
          alias bar_hash = hash 
```

we don't support:
```
   trait foo {
      use trait bar
          alias bar_eq(_) = ==(x), bar_hash = hash 
```

**Comment by apblack** [comment]
I agree, at least for now, that we should have multiple **alias** keywords, and multiple **uses** keywords.   We may want to reopen this after we have some experience using **uses** and **aliases**.
In general, it's hard to decide on the best thing to do here without some experience, but in order to get experience, we need an implementation, and in order to get an implementation, we need (provisional) decisions on these things.

**Comment by kjx** [comment]
so according to the protocol I wrote last week, this shouldn't be closed, but should be moved from "now" to "resolved, to be specd".   which I've now done.  sorry.

**Comment by apblack** [comment]
> the protocol I wrote last week

Where is this written?

**Comment by kjx** [comment]
I put it in the README.md of the repository, but only realised now that no-one ever looks at that.
I may have mentioned in the last minutes.
 
https://github.com/gracelang/language/blob/master/README.md

**Comment by kjx** [comment]
Andrew: Re-reading your comment, to clarify, multiple **exclude** clauses too each with one request name?  

https://github.com/gracelang/language/issues/43#issue-133507350

**Comment by kjx** [comment]
drafted - https://github.com/gracelang/language/blob/portland-james/spec.md#objects-classes-and-traits
