### ISSUE TITLE
descriptive or imperative: "use", "inherit" vs. "uses", "inherits"

### ISSUE THREAD

**Issue by kjx** [gracelang/language#61]
should we be consistent - move to **use** and **inherit**  

all other keywords are singular

**Comment by apblack** [comment]
To me, the issue is whether an object constructor is thought of as descriptive or imperative.  I've always thought of them as being descriptive, hence the right words are `inherits` and `uses`.  But of course, object constructors are not descriptive any more: they really do have an imperative semantics, and only an imperative semantics, because of initialization.

Traits are, in this respect, by attempt to walk back from that precipice — which is why I'm keep to exclude things from trait composition that can given only an imperative semantics.

If you agree with me, then we should really uses `aliases` and `excludes`.  Oh dear.

**Comment by kjx** [comment]
I agree with you about 50% - I hadn't thought of it that way but I now see what you mean. 
pragmatically, the question is whether we end with "s" or not. I can see two consistent sets:
 1. inherit, use, alias, exclude    _(my preference)_ 
 2. inherits, uses, aliases, excludes

**Comment by kjx** [comment]
we talked about this a bit.  I've moved back to "3: later" because other things are clearly more important.

**Comment by apblack** [comment]
I'm not so sure.  It's trivial to implement the change in the compiler and the spec; the problem is the body of code that we have published.

If we are going to make the change _someday_, it's better to make it _now_ for traits, when there is not much code out there (only the WadlerFest paper).  It will be confusing to make it for **inherits**, but it will only get _more_ confusing the longer we leave it.

So I think that we should either do it _now_, or forget about this idea for the foreseeable future.

**Comment by kjx** [comment]
> I'm not so sure. It's trivial to implement the change in the compiler and the spec; the problem is the body of code that we have published.

we've already made bigger changes (dotted to non-dotted classes).   I expect (somewhere between hope and dread) that the discipline of writing a spec, and then workshopping it, will drive other changes too. 

> If we are going to make the change someday, it's better to make it now for traits,

actually I agree; which is why I brought this up (also **type** vs **interface**) and the trait and inheritance semantics..

**Comment by KimBruce** [comment]
I prefer the consistent “s” suffix versions, as I prefer the descriptive sense to the definitions.

Kim

**Comment by kjx** [comment]
I'm not sure I see these as descriptive.  I don't see "I inherit from my parents" or "I exclude you from my club" as necessarily imperative statements.  

Most English programming languages seem to avoid keywords ending in "s".  Java has three exceptions to that convention: "extends" and "implements"  and "throws".  C# apparently has one: "params" - which is used to take a variadic argument list :-)   Python and Pascal have none.

**Comment by apblack** [comment]
I mis-spoke [above](https://github.com/gracelang/language/issues/61#issuecomment-189071227): the WadlerFest paper does not use **uses**, only **alias**.

When writing code, I've found it hard to remember to write **exclude** (rather than **excludes**), perhaps because I've just written **inherits** and **uses**.   This would argue for making the change, and using imperative forms uniformly.

Of course, **def** is ambiguous: it could mean "define" or "defines" or "definition".  In the end, these keywords become meaningless as words and take on a life of their own.  But while learning them, it might be easier if we were uniform with **inherit**, **use**, **alias**, and **exclude**.

**Comment by kjx** [comment]
The spec now goes with: 'use' 'inherit' 'alias' 'exclude' 

https://github.com/gracelang/language/blob/portland-james/spec.md#reserved-tokens

**Comment by KimBruce** [comment]
Really?  That breaks all my existing code!!  (Every program uses "inherits")

**Comment by kjx** [comment]
If we are to make changes like this one (or varargs, or getting rid of [] or whatever) then when?
