### ISSUE TITLE
What should the spec say about the "Self" type?

### ISSUE THREAD

**Issue by kjx** [gracelang/language#79]
See: https://github.com/gracelang/language/blob/portland-james/spec.md#type-self

**Comment by KimBruce** [comment]
How about something like this:

Self is a reserved word that refers to the type of self in an object, i.e., the full type of that object.
If Self is used in a class, then it refers to the type of self in any objects that it generates. If code referring to Self is inherited in a subclass, then those occurrences of Self will again refer to the type of self in the objects generated by the subclass.
--------
The last sentence isn't strictly necessary, but should be clarifying.  This definition provides the information needed for dynamic type checks.  It says nothing about static type checking because that will occur in a dialect.  Of course, some dialects may choose to ban the use of Self altogether.  Notice I described it as a reserved word, so that it may not be redefined by a user's program.

Let me know if you see any problems with this.

**Comment by kjx** [comment]
Ok - I have less text but with the same intent there now.  Look on the James-editing branch 

I am also trying to put brief comments on the conformance rules in there - they have been there (but not completely) for the other types. 

So we should say something about that if we can. 

J, on phone...

**Comment by kjx** [comment]
drafted here - https://github.com/gracelang/language/blob/portland-james/spec.md#type-self

**Comment by KimBruce** [comment]
I'm fine with this
